[project]
name = "myps"
version = "0.1.0"
description = "Process tree viewer for current user with filtering"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "psutil>=7.0.0",
    "rich>=14.1.0",
]

[project.scripts]
mypsc = "myps:cli.main"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"